default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: 5

development:
  <<: *default
  database: paypal_development

test:
  <<: *default
  database: paypal_test
